version: "3"
networks:
  public:

services:
  api:
    container_name: TheTiptop_Api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 4000:${PORT}
    networks:
      - public
    environment:
      - PORT=${PORT}
      - DBHOSTNAME=${DBHOSTNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/api
    depends_on:
      - db
    command: sh -c 'while ! nc -z db 3306; do sleep 1; done; npm run dev'
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #     command: ["pytest","test", "-v"] à modifier
  #   networks:
  #     - public
  #   environment:
  #   volumes:
  #     - .:/api
  #   stdin_open: true
  #   tty:true
  #   depends_on:
  #     - db
  db:
    container_name: TheTiptop_Db
    image: mysql:latest
    env_file:
      - .env
    ports:
      - 3307:3306
    networks:
      - public
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  dbtests:
    container_name: TheTiptop_DbTest
    image: mysql:latest
    env_file:
      - .env.test
    ports:
      - 3308:3306
    networks:
      - public
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data-test:/var/lib/mysql
volumes:
  mysql-data:
  mysql-data-test:
